- name: Install Composer globally
  shell: curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f composer.phar {{ composer_path }} creates={{ composer_path }}

- name: Copy PHP-FPM config
  template:
    src=www.conf
    dest=/etc/php-fpm.d/www.conf
  notify:
    - restart php-fpm
