 - hosts: web
   become: true
   vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../web"
    ansistrano_deploy_to: "/var/www"
    ansistrano_current_dir: "app"
    ansistrano_current_via: "symlink"
    ansistrano_version_dir: "releases" # Releases folder name
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: rsync
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/deploy/before-update-code-tasks.yml"
   roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }
  
  